name: notification_simple
description: "Simple project notification"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
assets:
  - assets/images/
